[package]
name = "dhcp"
version = "0.1.0"
authors = ["Paul Woolcock <paul@woolcock.us>"]

[dependencies]
nom = "*"
mio = "*"

[lib]
name = 'dhcp'
path = 'src/lib.rs'

[[bin]]
name = 'serve'
path = 'src/bin/serve.rs'
